apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '80'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 776431db4c3ea353ef2ece892ffb8a1f520aee8a5780919a5be2f6c4daf9d711
  name: adaptive-export
  namespace: pl
spec:
  architectures:
  - amd64
  capabilities:
  - CAP_NET_ADMIN
  egress:
  - dns: ''
    dnsNames: null
    identifier: 15e8bb325ab9693217dcc18f8a7f16c885f388f7e307ecfd0646aceed194f3d2
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: clickhouse
    podSelector:
      matchLabels:
        apps.kubernetes.io/pod-index: '0'
        clickhouse.altinity.com/app: chop
        clickhouse.altinity.com/chi: forensic-soc-db
        clickhouse.altinity.com/cluster: soc-cluster
        clickhouse.altinity.com/namespace: clickhouse
        clickhouse.altinity.com/ready: 'yes'
        clickhouse.altinity.com/replica: '0'
        clickhouse.altinity.com/shard: '0'
        statefulset.kubernetes.io/pod-name: chi-forensic-soc-db-soc-cluster-0-0-0
    ports:
    - name: TCP-8123
      port: 8123
      protocol: TCP
    type: internal
  - dns: work.test.austrianopencloudcommunity.org.
    dnsNames:
    - work.test.austrianopencloudcommunity.org.
    identifier: 284d617ca3e493147f79f2c7f185037100a9c2636930eec7995122394206e7fe
    ipAddress: 100.103.139.51
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-443
      port: 443
      protocol: TCP
    type: external
  - dns: ''
    dnsNames: null
    identifier: dd18fa52244005a49761004e6173ec450c0779087cedb1eaf1ae49142a6550a2
    ipAddress: 10.43.0.1
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: default
    podSelector:
      matchLabels:
        component: apiserver
        provider: kubernetes
    ports:
    - name: TCP-443
      port: 443
      protocol: TCP
    type: internal
  - dns: ''
    dnsNames: null
    identifier: 4380bec7cadc8df8f7321e3ceac7739db245e5db032c59fdb73c104aa0543112
    ipAddress: 10.43.0.10
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: internal
  endpoints: null
  execs:
  - args:
    - /app/src/vizier/services/adaptive_export/cmd/cmd
    path: /app/src/vizier/services/adaptive_export/cmd/cmd.runfiles/px/src/vizier/services/adaptive_export/cmd/cmd_/cmd
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress:
  - dns: ''
    dnsNames: null
    identifier: dx-control
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: honey
    podSelector:
      matchLabels:
        app: dx-daemon
    ports:
    - name: TCP-9100
      port: 9100
      protocol: TCP
    type: internal
  - dns: ''
    dnsNames: null
    identifier: dx-control-cidr
    ipAddress: ''
    ipAddresses:
    - 10.42.0.0/16
    - 10.43.0.0/16
    - 10.244.0.0/16
    - 10.96.0.0/12
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-9100
      port: 9100
      protocol: TCP
    type: internal
  matchLabels:
    name: adaptive-export
  opens:
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /*/maps
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /*/net/core/somaxconn
  - flags:
    - O_RDONLY
    - O_DIRECTORY
    - O_CLOEXEC
    path: /*/task/⋯/fd
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /⋯
  - flags:
    - O_CLOEXEC
    - O_DIRECTORY
    - O_RDONLY
    path: /⋯/*
  rulePolicies:
    R0001:
      processAllowed:
      - runc
    R0002:
      processAllowed:
      - runc
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls:
  - accept4
  - access
  - arch_prctl
  - bind
  - brk
  - capget
  - capset
  - chdir
  - clone3
  - close
  - close_range
  - connect
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - eventfd2
  - execve
  - exit
  - faccessat2
  - fcntl
  - fstat
  - fstatfs
  - futex
  - getcwd
  - getdents64
  - getpeername
  - getpid
  - getppid
  - getrandom
  - getsockname
  - getsockopt
  - gettid
  - ioctl
  - listen
  - madvise
  - mmap
  - mprotect
  - munmap
  - nanosleep
  - newfstatat
  - openat
  - openat2
  - prctl
  - pread64
  - prlimit64
  - read
  - readlinkat
  - recvfrom
  - rseq
  - rt_sigaction
  - rt_sigprocmask
  - rt_sigreturn
  - sched_getaffinity
  - sched_yield
  - set_robust_list
  - set_tid_address
  - setgid
  - setgroups
  - setsockopt
  - setuid
  - sigaltstack
  - socket
  - statx
  - tgkill
  - tkill
  - uname
  - write
