apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '12'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 6d0e27ce19ce58ce1c71bfc592de2d4ae6d9ee9dad8d205e8c35d34a5aa4a5ba
  name: cert-provisioner-job-provisioner
  namespace: pl
spec:
  architectures: null
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  egress: null
  endpoints: null
  execs:
  - path: /app/src/utils/cert_provisioner/cert_provisioner.runfiles/px/src/utils/cert_provisioner/cert_provisioner_/cert_provisioner
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress: null
  opens:
  - flags: null
    path: /*
  - flags: null
    path: /*/fd
  - flags: null
    path: /*/libm.so.6
  - flags: null
    path: /*/x86-64-v2/libm.so.6
  - flags: null
    path: /*/x86-64-v3/libm.so.6
  - flags: null
    path: /*/x86_64/libm.so.6
  - flags: null
    path: /*/x86_64/x86_64/libm.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /⋯
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /⋯/*
  rulePolicies:
    R0001:
      processAllowed:
      - runc
    R0002:
      processAllowed:
      - runc
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls: null
