apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/status: completed
  name: catalog-operator
  namespace: olm
spec:
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_NET_ADMIN
  egress:
  - identifier: 2297897752f7953edd031ddd6f824a44163c479b649d3db6fef80eff7303dcd2
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: px-operator
    podSelector:
      matchLabels:
        olm.catalogSource: pixie-operator-index
        olm.managed: 'true'
    ports:
    - name: TCP-50051
      port: 50051
      protocol: TCP
  - identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: honey
    podSelector:
      matchLabels:
        app: node-agent
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: catalog-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: olm-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kubernetes
    serviceRefNamespace: default
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kube-dns
    serviceRefNamespace: kube-system
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-metadata-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-query-broker-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-cloud-connector-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats-mgmt
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kelvin-service
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: wildcard-any-address
    ipAddresses:
    - '*'
    ports: null
    type: ''
  - dns: ''
    dnsNames:
    - '*.cluster.local'
    - '*.svc'
    - '*.local'
    - '*.com'
    - '*.org'
    - '*.net'
    - '*.io'
    - '*.dev'
    - '*.arpa'
    identifier: wildcard-any-dns
    ports: null
    type: ''
  execs:
  - path: /bin/catalog
  ingress:
  - identifier: 209567a3863579abd33381b8530e8ba80051db1f3ed6c9cf0672c6b27ab4e936
    ipAddress: 10.42.1.1
    ports:
    - name: TCP-8080
      port: 8080
      protocol: TCP
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: honey
    podSelector:
      matchLabels:
        app: node-agent
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: catalog-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: olm-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kubernetes
    serviceRefNamespace: default
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kube-dns
    serviceRefNamespace: kube-system
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-metadata-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-query-broker-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-cloud-connector-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats-mgmt
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kelvin-service
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    entity: host
    identifier: ''
    ipAddress: ''
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddresses:
    - 10.42.0.1
    - 10.42.1.1
    - 10.42.2.1
    - 10.42.3.1
    - 10.42.4.1
    - 10.42.5.1
    - 10.42.6.1
    - 10.42.7.1
    ports:
    - name: TCP-8080
      port: 8080
      protocol: TCP
    - name: TCP-8081
      port: 8081
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: wildcard-any-address
    ipAddresses:
    - '*'
    ports: null
    type: ''
  - dns: ''
    dnsNames:
    - '*.cluster.local'
    - '*.svc'
    - '*.local'
    - '*.com'
    - '*.org'
    - '*.net'
    - '*.io'
    - '*.dev'
    - '*.arpa'
    identifier: wildcard-any-dns
    ports: null
    type: ''
  opens:
  - path: /etc/hosts
  - path: /etc/localtime
  - path: /etc/nsswitch.conf
  - path: /etc/passwd
  - path: /etc/resolv.conf
  - path: /opt/hostedtoolcache/go/1.21.7/x64/lib/time/zoneinfo.zip
  - path: "/proc/\u22EF/kernel/cap_last_cap"
  - path: "/proc/\u22EF/net/core/somaxconn"
  - path: "/proc/\u22EF/task/1/fd"
  - path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/ca.crt"
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/token"
  syscalls:
  - accept4
  - close
  - epoll_ctl
  - epoll_pwait
  - fcntl
  - fstat
  - futex
  - getpid
  - getrandom
  - getsockname
  - ioctl
  - madvise
  - nanosleep
  - openat
  - read
  - rt_sigreturn
  - sched_yield
  - setsockopt
  - tgkill
  - write
