apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '52'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: b00caecfa3a49792a9a9c9a341d79e0f3a32324b0503e13ac252eadb116b3ef2
  name: kelvin-qb-wait
  namespace: pl
spec:
  architectures: null
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_SETGID
  - CAP_SETUID
  egress:
  - dns: ''
    dnsNames: null
    identifier: ceb1bd1c4e29911ce508482bd2e727fce6fe7e157ae0d62e4b5cce145343ff16
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: pl-monitoring
        component: vizier
        name: vizier-query-broker
    ports:
    - name: TCP-50300
      port: 50300
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: ''
  endpoints: null
  execs:
  - path: /bin/busybox
  - path: /usr/bin/curl
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress: null
  opens:
  - flags: null
    path: /*
  - flags: null
    path: /*/1/fd
  - flags: null
    path: /*/openssl.cnf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /⋯
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /⋯/*
  rulePolicies:
    R0001:
      processAllowed:
      - runc
    R0002:
      processAllowed:
      - runc
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls:
  - arch_prctl
  - capget
  - capset
  - close_range
  - dup2
  - epoll_ctl
  - epoll_pwait
  - eventfd2
  - exit
  - exit_group
  - faccessat2
  - fork
  - fstatfs
  - futex
  - getdents64
  - getegid
  - geteuid
  - getgid
  - gettid
  - getuid
  - membarrier
  - newfstatat
  - open
  - openat
  - openat2
  - pipe
  - pipe2
  - poll
  - prctl
  - recvmsg
  - sendto
  - set_tid_address
  - setgroups
  - stat
  - statx
  - tkill
  - unknown
  - wait4
  - writev
