apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '13'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: b31625c901fe71245c7d71d32fa07f578332e074bc6e6c8ebdd4242ab5b81f25
  name: kelvin-cc-wait
  namespace: pl
spec:
  architectures: null
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_SETGID
  - CAP_SETUID
  egress:
  - dns: ''
    dnsNames: null
    identifier: 1d2583e844b97eb29d04a65d1cb93e01802876106b2633e8a2426a53bfd75f77
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: pl-monitoring
        component: vizier
        name: vizier-cloud-connector
        vizier-bootstrap: 'true'
    ports:
    - name: TCP-50800
      port: 50800
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: honey
    podSelector:
      matchLabels:
        app: node-agent
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: catalog-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: olm-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kubernetes
    serviceRefNamespace: default
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kube-dns
    serviceRefNamespace: kube-system
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-metadata-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-query-broker-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-cloud-connector-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats-mgmt
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kelvin-service
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: wildcard-any-address
    ipAddresses:
    - '*'
    ports: null
    type: ''
  - dns: ''
    dnsNames:
    - '*.cluster.local'
    - '*.svc'
    - '*.local'
    - '*.com'
    - '*.org'
    - '*.net'
    - '*.io'
    - '*.dev'
    - '*.arpa'
    - '*.pod.cluster.local'
    - '*.svc.cluster.local'
    - '*.in-addr.arpa'
    - '*.ip6.arpa'
    - '*.cluster.local.'
    - '*.pl.pod.cluster.local'
    - '*.honey.pod.cluster.local'
    - '*.olm.pod.cluster.local'
    - '*.px-operator.pod.cluster.local'
    - '*.shop.pod.cluster.local'
    - '*.kube-system.pod.cluster.local'
    - '*.clickhouse.pod.cluster.local'
    - '*.default.pod.cluster.local'
    - '*.kube-public.pod.cluster.local'
    - '*.kube-node-lease.pod.cluster.local'
    - '*.pl.svc.cluster.local'
    - '*.honey.svc.cluster.local'
    - '*.olm.svc.cluster.local'
    - '*.px-operator.svc.cluster.local'
    - '*.shop.svc.cluster.local'
    - '*.kube-system.svc.cluster.local'
    - '*.clickhouse.svc.cluster.local'
    - '*.default.svc.cluster.local'
    - '*.kube-public.svc.cluster.local'
    - '*.kube-node-lease.svc.cluster.local'
    - '*.pl.pod.cluster.local.'
    - '*.honey.pod.cluster.local.'
    - '*.olm.pod.cluster.local.'
    - '*.px-operator.pod.cluster.local.'
    - '*.shop.pod.cluster.local.'
    - '*.kube-system.pod.cluster.local.'
    - '*.clickhouse.pod.cluster.local.'
    - '*.default.pod.cluster.local.'
    - '*.kube-public.pod.cluster.local.'
    - '*.kube-node-lease.pod.cluster.local.'
    - '*.pl.svc.cluster.local.'
    - '*.honey.svc.cluster.local.'
    - '*.olm.svc.cluster.local.'
    - '*.px-operator.svc.cluster.local.'
    - '*.shop.svc.cluster.local.'
    - '*.kube-system.svc.cluster.local.'
    - '*.clickhouse.svc.cluster.local.'
    - '*.default.svc.cluster.local.'
    - '*.kube-public.svc.cluster.local.'
    - '*.kube-node-lease.svc.cluster.local.'
    identifier: wildcard-any-dns
    ports: null
    type: ''
  endpoints: null
  execs:
  - path: /bin/busybox
  - path: /usr/bin/curl
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress:
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: honey
    podSelector:
      matchLabels:
        app: node-agent
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: catalog-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: olm-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kubernetes
    serviceRefNamespace: default
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kube-dns
    serviceRefNamespace: kube-system
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-metadata-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-query-broker-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-cloud-connector-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats-mgmt
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kelvin-service
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    entity: host
    identifier: ''
    ipAddress: ''
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: wildcard-any-address
    ipAddresses:
    - '*'
    ports: null
    type: ''
  - dns: ''
    dnsNames:
    - '*.cluster.local'
    - '*.svc'
    - '*.local'
    - '*.com'
    - '*.org'
    - '*.net'
    - '*.io'
    - '*.dev'
    - '*.arpa'
    - '*.pod.cluster.local'
    - '*.svc.cluster.local'
    - '*.in-addr.arpa'
    - '*.ip6.arpa'
    - '*.cluster.local.'
    - '*.pl.pod.cluster.local'
    - '*.honey.pod.cluster.local'
    - '*.olm.pod.cluster.local'
    - '*.px-operator.pod.cluster.local'
    - '*.shop.pod.cluster.local'
    - '*.kube-system.pod.cluster.local'
    - '*.clickhouse.pod.cluster.local'
    - '*.default.pod.cluster.local'
    - '*.kube-public.pod.cluster.local'
    - '*.kube-node-lease.pod.cluster.local'
    - '*.pl.svc.cluster.local'
    - '*.honey.svc.cluster.local'
    - '*.olm.svc.cluster.local'
    - '*.px-operator.svc.cluster.local'
    - '*.shop.svc.cluster.local'
    - '*.kube-system.svc.cluster.local'
    - '*.clickhouse.svc.cluster.local'
    - '*.default.svc.cluster.local'
    - '*.kube-public.svc.cluster.local'
    - '*.kube-node-lease.svc.cluster.local'
    - '*.pl.pod.cluster.local.'
    - '*.honey.pod.cluster.local.'
    - '*.olm.pod.cluster.local.'
    - '*.px-operator.pod.cluster.local.'
    - '*.shop.pod.cluster.local.'
    - '*.kube-system.pod.cluster.local.'
    - '*.clickhouse.pod.cluster.local.'
    - '*.default.pod.cluster.local.'
    - '*.kube-public.pod.cluster.local.'
    - '*.kube-node-lease.pod.cluster.local.'
    - '*.pl.svc.cluster.local.'
    - '*.honey.svc.cluster.local.'
    - '*.olm.svc.cluster.local.'
    - '*.px-operator.svc.cluster.local.'
    - '*.shop.svc.cluster.local.'
    - '*.kube-system.svc.cluster.local.'
    - '*.clickhouse.svc.cluster.local.'
    - '*.default.svc.cluster.local.'
    - '*.kube-public.svc.cluster.local.'
    - '*.kube-node-lease.svc.cluster.local.'
    identifier: wildcard-any-dns
    ports: null
    type: ''
  opens:
  - flags: null
    path: /*
  - flags: null
    path: /*/1/fd
  - flags: null
    path: /*/openssl.cnf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: "/\u22EF"
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: "/\u22EF/*"
  rulePolicies:
    R0001:
      processAllowed:
      - runc
    R0002:
      processAllowed:
      - runc
    R0011:
      processAllowed:
      - busybox
      - curl
      - sh
    R0012:
      processAllowed:
      - busybox
      - curl
      - sh
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls: null
