apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/status: completed
  name: olm-operator
  namespace: olm
spec:
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_NET_ADMIN
  egress:
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: honey
    podSelector:
      matchLabels:
        app: node-agent
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: catalog-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: olm-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kubernetes
    serviceRefNamespace: default
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kube-dns
    serviceRefNamespace: kube-system
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-metadata-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-query-broker-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-cloud-connector-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats-mgmt
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kelvin-service
    serviceRefNamespace: pl
    type: ''
  execs:
  - path: /bin/olm
  ingress:
  - identifier: 0a52270744d47da0e770b43cf46a02db90adfdaed097b34c8eacf9c267793a14
    ipAddress: 10.42.0.1
    ports:
    - name: TCP-8080
      port: 8080
      protocol: TCP
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: honey
    podSelector:
      matchLabels:
        app: node-agent
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: catalog-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: olm
    podSelector:
      matchLabels:
        app: olm-operator
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kubernetes
    serviceRefNamespace: default
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kube-dns
    serviceRefNamespace: kube-system
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-metadata-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-query-broker-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: vizier-cloud-connector-svc
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: pl-nats-mgmt
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddress: ''
    ports: null
    serviceRefName: kelvin-service
    serviceRefNamespace: pl
    type: ''
  - dns: ''
    dnsNames: null
    entity: host
    identifier: ''
    ipAddress: ''
    ports: null
    type: ''
  - dns: ''
    dnsNames: null
    identifier: ''
    ipAddresses:
    - 10.42.0.1
    - 10.42.1.1
    - 10.42.2.1
    - 10.42.3.1
    - 10.42.4.1
    - 10.42.5.1
    - 10.42.6.1
    - 10.42.7.1
    ports:
    - name: TCP-8080
      port: 8080
      protocol: TCP
    - name: TCP-8081
      port: 8081
      protocol: TCP
    type: ''
  opens:
  - path: /etc/localtime
  - path: /etc/passwd
  - path: /opt/hostedtoolcache/go/1.21.7/x64/lib/time/zoneinfo.zip
  - path: "/proc/\u22EF/kernel/cap_last_cap"
  - path: "/proc/\u22EF/net/core/somaxconn"
  - path: "/proc/\u22EF/task/1/fd"
  - path: /sys/kernel/mm/transparent_hugepage/hpage_pmd_size
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/ca.crt"
  - path: "/var/run/secrets/kubernetes.io/serviceaccount/\u22EF/token"
  syscalls:
  - accept4
  - arch_prctl
  - bind
  - capget
  - capset
  - chdir
  - clone
  - close
  - close_range
  - connect
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - execve
  - exit
  - faccessat2
  - fchown
  - fcntl
  - fstat
  - fstatfs
  - futex
  - getcwd
  - getdents64
  - getgid
  - getpeername
  - getpid
  - getppid
  - getrandom
  - getrlimit
  - getsockname
  - getsockopt
  - gettid
  - getuid
  - ioctl
  - listen
  - madvise
  - mmap
  - munmap
  - nanosleep
  - newfstatat
  - openat
  - openat2
  - pipe2
  - prctl
  - pread64
  - read
  - readlinkat
  - recvfrom
  - rt_sigaction
  - rt_sigprocmask
  - rt_sigreturn
  - sched_getaffinity
  - sched_yield
  - setgid
  - setgroups
  - setsockopt
  - setuid
  - sigaltstack
  - socket
  - statfs
  - statx
  - tgkill
  - tkill
  - uname
  - unknown
  - write
