# SBoB for vizier-metadata/nats-wait — generalised from a recorded ContainerProfile.
# opens 63 -> 9 after collapse+portability.
apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  name: vizier-metadata-nats-wait
  namespace: pl
  annotations:
    kubescape.io/managed-by: User
spec:
  execs:
  - path: /bin/busybox
  - path: /usr/bin/curl
  opens:
  - path: /.config/curlrc
  - path: /.curlrc
  - path: /dev/null
  - path: /etc/⋯
  - path: /etc/⋯/openssl.cnf
  - path: /lib/⋯
  - path: /proc/⋯/1/fd
  - path: /usr/lib/⋯
  - path: /usr/local/lib/⋯
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_SETGID
  - CAP_SETUID
  egress:
  - identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    ports:
    - name: UDP-53
      protocol: UDP
      port: 53
  - identifier: 63f25e9f7fe5fae0febfbde38ab9003eaeaedafbf0403e6ffa8e6ed956b62c4c
    podSelector:
      matchLabels:
        app: pl-monitoring
        name: pl-nats
        plane: control
        vizier-name: pixie
    ports:
    - name: TCP-8222
      protocol: TCP
      port: 8222
