apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '48'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 45431006395899e477c67185302a10e0f0dde546eb17faf6be212356520b1a4d
  name: vizier-query-broker
  namespace: pl
spec:
  architectures: null
  capabilities:
  - CAP_FOWNER
  - CAP_NET_ADMIN
  egress:
  - dns: ''
    dnsNames: null
    identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: d9bcc711b1fbffffc6fe9bdacd6057f0b6c5d58863f85bded6d7fb18c18bd077
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: pl-monitoring
        component: vizier
        name: vizier-metadata
    ports:
    - name: TCP-50400
      port: 50400
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: a08590764670db9042dbda79f3deaa0eee333ec6950ccadc5dd0262fcd994e42
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: pl-monitoring
        name: pl-nats
    ports:
    - name: TCP-4222
      port: 4222
      protocol: TCP
    type: ''
  endpoints: null
  execs:
  - path: /app/src/vizier/services/query_broker/query_broker.runfiles/px/src/vizier/services/query_broker/query_broker_/query_broker
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress:
  - dns: ''
    dnsNames: null
    identifier: 0a52270744d47da0e770b43cf46a02db90adfdaed097b34c8eacf9c267793a14
    ipAddress: 10.42.0.1
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-50300
      port: 50300
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: 47a42bd64869e8ed568c98f218ab5d89ea818764568dffb66fe316abd30926cf
    ipAddress: 10.42.1.0
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-50300
      port: 50300
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: 62ee591d43b945c22a6b4d20155af717cb843a2b85b56ded1939857603480152
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: pl-monitoring
        component: vizier
        name: kelvin
        plane: data
        vizier-name: pixie
    ports:
    - name: TCP-50300
      port: 50300
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: c46150dd8f613da582a6de01611c631d866f1f6566191aa88f5807ec76f2c26e
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: pl-monitoring
        cluster-id: 6a59ca82-ebaa-4bcd-88b2-41ae2678d72f
        component: vizier
        name: vizier-cloud-connector
        plane: control
        vizier-bootstrap: 'true'
        vizier-name: pixie
    ports:
    - name: TCP-50300
      port: 50300
      protocol: TCP
    type: ''
  opens:
  - flags: null
    path: /*
  - flags: null
    path: /*/fd
  - flags: null
    path: /*/libm.so.6
  - flags: null
    path: /*/somaxconn
  - flags: null
    path: /*/x86-64-v2/libm.so.6
  - flags: null
    path: /*/x86-64-v3/libm.so.6
  - flags: null
    path: /*/x86_64/libm.so.6
  - flags: null
    path: /*/x86_64/x86_64/libm.so.6
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /⋯
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /⋯/*
  rulePolicies:
    R0001:
      processAllowed:
      - runc
    R0002:
      processAllowed:
      - runc
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls:
  - accept4
  - brk
  - close
  - connect
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - futex
  - getpeername
  - getpid
  - getrandom
  - getsockname
  - getsockopt
  - gettid
  - lseek
  - madvise
  - mincore
  - mmap
  - nanosleep
  - read
  - readlinkat
  - rt_sigprocmask
  - rt_sigreturn
  - sched_yield
  - setsockopt
  - socket
  - tgkill
  - write
