apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '36'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: bb2c9b66980b0b29581d5650b77fb6c92ab3a6c785f5281ff1e1d9a73543f719
  name: vizier-query-broker-mds-wait
  namespace: pl
spec:
  architectures: null
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_SETGID
  - CAP_SETUID
  egress:
  - dns: ''
    dnsNames: null
    identifier: d9bcc711b1fbffffc6fe9bdacd6057f0b6c5d58863f85bded6d7fb18c18bd077
    ipAddress: ''
    namespaceSelector: null
    podSelector:
      matchLabels:
        app: pl-monitoring
        component: vizier
        name: vizier-metadata
    ports:
    - name: TCP-50400
      port: 50400
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: ''
  endpoints: null
  execs:
  - path: /bin/busybox
  - path: /usr/bin/curl
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress: null
  opens:
  - flags: null
    path: /*
  - flags: null
    path: /*/1/fd
  - flags: null
    path: /*/openssl.cnf
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /⋯
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /⋯/*
  rulePolicies:
    R0001:
      processAllowed:
      - runc
    R0002:
      processAllowed:
      - runc
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls:
  - capget
  - capset
  - chdir
  - exit
  - exit_group
  - fchown
  - fstatfs
  - getcwd
  - getdents64
  - getegid
  - geteuid
  - getppid
  - gettid
  - membarrier
  - newfstatat
  - prctl
  - recvfrom
  - sendto
  - set_tid_address
  - setgroups
  - sigaltstack
  - tkill
  - wait4
