apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: storage-auth-reader
  namespace: kube-system
  annotations: null
  labels:
    helm.sh/chart: kubescape-operator-1.30.2
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/instance: kubescape
    app.kubernetes.io/component: storage
    app.kubernetes.io/version: 1.30.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kubescape
    app: storage
    tier: ks-control-plane
    kubescape.io/ignore: 'true'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: storage
  namespace: honey
