# yamllint disable-file
apiVersion: ENC[AES256_GCM,data:77g=,iv:B2qWMIT6+yRQN2uaSsBwIfMYKSGas1hN2aDRNZr/dQk=,tag:/q45kUgx95OBRZ6Qln95DA==,type:str]
kind: ENC[AES256_GCM,data:H1F5mgPS,iv:8Xqz2FBgEdwx0NyDifOn9g3R7ZzgGU5S/Pdqppj5JoQ=,tag:22q5esTXqBp55cxL3oygeg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:btjpA+ZkOIXEQF6Wv5bbXqVMfw==,iv:l0HSDb0YHm1cO4kHeyoXnmnmahiftXzRHGhWV3DRwIs=,tag:8b2J9sUHSbU8W+Z0G3eS6w==,type:str]
    namespace: ENC[AES256_GCM,data:2oW6zrlbVw==,iv:NIj5ACNbvslHwqsmp2dlWLWP5BazrkzPkRl+JFdH/V8=,tag:rlQE6NOJ5gRNwwLXClkKuw==,type:str]
type: ENC[AES256_GCM,data:S+1W7pp0,iv:QTo9fKwQOqAB35EheMtjdMDMFjxhSTzWAn+8qUQebMQ=,tag:/VlO8i7g3h82cMR+cQRoOw==,type:str]
stringData:
    auth0-client-id: ENC[AES256_GCM,data:EJhlEzbMYIU2HxqEUT9SQl+tkfNT6Uz/XbvGjD1s08Q=,iv:ggsAPGqS2XkXfAg6C7QIIuULIYt2BUTDdlTwv20dcbA=,tag:jZhPvYK1Ir0byz4SNG8lnA==,type:str]
    auth0-client-secret: ENC[AES256_GCM,data:sFsh5s72IUuQUwXTjf7a/yjT9GYimSKsVBtyc2tg4vQhDKkLVi/pJexg7Koq8+rQM9RfsIHBxywQwBZhIIRolg==,iv:N/Y+qXpwXYZimyi8UO5wKlg4MyWvDRvyz5Hliz0etLo=,tag:mO/zHqqVdWSzM0/N80dl4A==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-pixie-cloud.vault.azure.net
          name: sops-key
          version: b97b0a7fdebf4159a7319ad2ac6797fc
          created_at: "2026-02-19T02:28:57Z"
          enc: VygMiN49sSv1UNtGdFlj3Dq5tkWf8UEvTSecpkO7pu4MXdLArSVWVSIqiU0tqFzhVUDY9eHJDce4Mcg3y72RwqSSr-az6ue7pbCHYok1odrm8_X11im5xxU9P15cMyc9yOdmEU17xXazdMVeXMcjbghuc_BgNK1WY0KnuaaawF-2QfbPVteDkIGEMcFtYDDxE9UknU6AIBfFyejnhlsdG-0PmaVKQeQk94hw5z9Ol1bwBrcwREYH_6fhemyW54knVsByUN6kWjTl4eo1hanQsD7xeed1bKlFyaPdPjqnDk9aTG9aecCqFgiU1gDPdXF1WtHOYkE8ZHCgoZUM7j-sHQ
    lastmodified: "2026-02-19T02:29:00Z"
    mac: ENC[AES256_GCM,data:Sd0sbwGCkkTVt21q2SFrv4St4OCfX2ugjQBFLX6B+HgH9RtaqY+/zu3M/o0NwjffkBFSTyPuv6W+QICGuesOPgB88Tv3saySytpTlBvyEIFQ5/8odWHnnOzz5ZY8UeQJVh/3Se3CYcLBWLOkKInn0Ka4gMWcNboHNAnEhfytR5s=,iv:+5khmIICAaSxa+PnUZUw67CL8hARuwlqKhv0JbGIm+g=,tag:F8AQTH28cQyoHOKNZ33Lmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
