# This file is automatically generated via the Auth0 CLI.
# It can be safely removed after the successful generation
# of Terraform resource definition files.

import {
  id = "e5ebee0e-0ac3-4f58-bd5b-c375377c9b24"
  to = auth0_attack_protection.attack_protection
}

import {
  id = "b669af3f-2d77-4205-92f3-76140f856208"
  to = auth0_branding.branding
}

import {
  id = "5akM0SumJG95tcRlP390pXzJoZkkYNDT"
  to = auth0_client.sovereignsoc_pixie_cloud
}

import {
  id = "5akM0SumJG95tcRlP390pXzJoZkkYNDT"
  to = auth0_client_credentials.sovereignsoc_pixie_cloud
}

import {
  id = "cgr_lgvjTwTNm53mojKq"
  to = auth0_client_grant.akm0sumjg95tcrlp390pxzjozkkyndt_https_k8sstormcenter_eu_auth0_com_api_v2
}

import {
  id = "con_gq4skrvMx0vH9Ocv"
  to = auth0_connection.google_oauth2
}

import {
  id = "con_gq4skrvMx0vH9Ocv"
  to = auth0_connection_clients.google_oauth2
}

import {
  id = "con_3HhKvUUeZr2ijQ90"
  to = auth0_connection.username_password_authentication
}

import {
  id = "con_3HhKvUUeZr2ijQ90"
  to = auth0_connection_clients.username_password_authentication
}

import {
  id = "18c8f86c-568f-489b-9eb7-5e7f91159985"
  to = auth0_guardian.guardian
}

import {
  id = "2fab16a6-8ff1-462b-b109-7233fc6acb35"
  to = auth0_pages.pages
}

import {
  id = "6abbc880-c36f-4503-a368-f35ad65aee3b"
  to = auth0_prompt.prompts
}

import {
  id = "login::en"
  to = auth0_prompt_custom_text.en_login
}

import {
  id = "login-id::en"
  to = auth0_prompt_custom_text.en_login_id
}

import {
  id = "login-password::en"
  to = auth0_prompt_custom_text.en_login_password
}

import {
  id = "login-email-verification::en"
  to = auth0_prompt_custom_text.en_login_email_verification
}

import {
  id = "signup::en"
  to = auth0_prompt_custom_text.en_signup
}

import {
  id = "signup-id::en"
  to = auth0_prompt_custom_text.en_signup_id
}

import {
  id = "signup-password::en"
  to = auth0_prompt_custom_text.en_signup_password
}

import {
  id = "reset-password::en"
  to = auth0_prompt_custom_text.en_reset_password
}

import {
  id = "consent::en"
  to = auth0_prompt_custom_text.en_consent
}

import {
  id = "mfa-push::en"
  to = auth0_prompt_custom_text.en_mfa_push
}

import {
  id = "mfa-otp::en"
  to = auth0_prompt_custom_text.en_mfa_otp
}

import {
  id = "mfa-voice::en"
  to = auth0_prompt_custom_text.en_mfa_voice
}

import {
  id = "mfa-phone::en"
  to = auth0_prompt_custom_text.en_mfa_phone
}

import {
  id = "mfa-webauthn::en"
  to = auth0_prompt_custom_text.en_mfa_webauthn
}

import {
  id = "mfa-sms::en"
  to = auth0_prompt_custom_text.en_mfa_sms
}

import {
  id = "mfa-email::en"
  to = auth0_prompt_custom_text.en_mfa_email
}

import {
  id = "mfa-recovery-code::en"
  to = auth0_prompt_custom_text.en_mfa_recovery_code
}

import {
  id = "mfa::en"
  to = auth0_prompt_custom_text.en_mfa
}

import {
  id = "status::en"
  to = auth0_prompt_custom_text.en_status
}

import {
  id = "device-flow::en"
  to = auth0_prompt_custom_text.en_device_flow
}

import {
  id = "email-verification::en"
  to = auth0_prompt_custom_text.en_email_verification
}

import {
  id = "email-otp-challenge::en"
  to = auth0_prompt_custom_text.en_email_otp_challenge
}

import {
  id = "organizations::en"
  to = auth0_prompt_custom_text.en_organizations
}

import {
  id = "invitation::en"
  to = auth0_prompt_custom_text.en_invitation
}

import {
  id = "common::en"
  to = auth0_prompt_custom_text.en_common
}

import {
  id = "email-identifier-challenge::en"
  to = auth0_prompt_custom_text.en_email_identifier_challenge
}

import {
  id = "passkeys::en"
  to = auth0_prompt_custom_text.en_passkeys
}

import {
  id = "login-passwordless::en"
  to = auth0_prompt_custom_text.en_login_passwordless
}

import {
  id = "phone-identifier-enrollment::en"
  to = auth0_prompt_custom_text.en_phone_identifier_enrollment
}

import {
  id = "phone-identifier-challenge::en"
  to = auth0_prompt_custom_text.en_phone_identifier_challenge
}

import {
  id = "custom-form::en"
  to = auth0_prompt_custom_text.en_custom_form
}

import {
  id = "customized-consent::en"
  to = auth0_prompt_custom_text.en_customized_consent
}

import {
  id = "logout::en"
  to = auth0_prompt_custom_text.en_logout
}

import {
  id = "captcha::en"
  to = auth0_prompt_custom_text.en_captcha
}

import {
  id = "brute-force-protection::en"
  to = auth0_prompt_custom_text.en_brute_force_protection
}

import {
  id = "69947cd1be21a17f3b9f7d5b"
  to = auth0_resource_server.auth0_management_api
}

import {
  id = "69947cd1be21a17f3b9f7d5b"
  to = auth0_resource_server_scopes.auth0_management_api
}

import {
  id = "96f40177-8ba2-4f05-aa75-3c6e3c824cb2"
  to = auth0_tenant.tenant
}

import {
  id = "customized-consent:customized-consent"
  to = auth0_prompt_screen_partial.customized_consent_customized_consent
}

import {
  id = "login:login"
  to = auth0_prompt_screen_partial.login_login
}

import {
  id = "login-id:login-id"
  to = auth0_prompt_screen_partial.login_id_login_id
}

import {
  id = "login-password:login-password"
  to = auth0_prompt_screen_partial.login_password_login_password
}

import {
  id = "login-passwordless:login-passwordless-sms-otp"
  to = auth0_prompt_screen_partial.login_passwordless_login_passwordless_sms_otp
}

import {
  id = "login-passwordless:login-passwordless-email-code"
  to = auth0_prompt_screen_partial.login_passwordless_login_passwordless_email_code
}

import {
  id = "signup:signup"
  to = auth0_prompt_screen_partial.signup_signup
}

import {
  id = "signup-id:signup-id"
  to = auth0_prompt_screen_partial.signup_id_signup_id
}

import {
  id = "signup-password:signup-password"
  to = auth0_prompt_screen_partial.signup_password_signup_password
}

