---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pl-artifact-config
data:
  PL_ARTIFACT_MANIFEST_URL: https://k8sstormcenter.github.io/pixie/artifacts/manifest.json
  PL_ARTIFACT_BUCKET: ""
  PL_SA_KEY_PATH: ""
