---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc
replicas:
- name: api-server
  count: 1
- name: auth-server
  count: 1
- name: profile-server
  count: 1
- name: cloud-proxy
  count: 1
- name: project-manager-server
  count: 1
- name: vzmgr-server
  count: 1
- name: scriptmgr-server
  count: 1
resources:
- ../../k8s/cloud/base
- cloud_ingress.yaml
- servers_transport.yaml
- proxy_service.yaml
- vzconn_service.yaml
- plugin_db_updater_job.yaml
labels:
- includeSelectors: true
  pairs:
    app: pl-cloud
patches:
- path: auth_deployment.yaml
- path: domain_config.yaml
- path: script_bundles_config.yaml
- path: proxy_envoy.yaml
- target:
    kind: Service
    name: api-service
  patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: api-service
      annotations:
        traefik.ingress.kubernetes.io/service.serverstransport: plc-cloud-backend-transport@kubernetescrd
        traefik.ingress.kubernetes.io/service.serversscheme: https
