---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc
resources:
- ../../k8s/cloud/public/base
- cloud_ingress_https.yaml
- cloud_ingress_grpcs.yaml
- servers_transport.yaml
patches:
# This ConfigMap is provided in terraform since it must be
# sops decrypted.
- target:
    kind: ConfigMap
    name: pl-oauth-config
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pl-oauth-config
- path: auth_deployment.yaml
- target:
    kind: Service
    name: cloud-proxy-service
  patch: |-
    - op: replace
      path: /spec/type
      value: ClusterIP
    - op: remove
      path: /metadata/annotations
- target:
    kind: Service
    name: vzconn-service
  patch: |-
    - op: replace
      path: /spec/type
      value: ClusterIP
    - op: remove
      path: /metadata/annotations
