---
# Empty user-defined ApplicationProfile for the postgres container. See
# redis-sbob.yaml for the rationale; same pattern, container name `postgres`
# matches postgres.yaml.
apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  name: postgres-empty
  namespace: redis
spec:
  architectures:
  - amd64
  containers:
  - name: postgres
    capabilities: null
    endpoints:    null
    execs:        null
    opens:        null
    syscalls:     null
    rulePolicies: {}
