apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '76'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 61bedc417d5ea0fe5ad1137cf9b3ff99788bd01bf7e2b8c3800b33631f4cbd4f
  name: olm-operator
  namespace: olm
spec:
  architectures: null
  capabilities:
  - CAP_DAC_OVERRIDE
  - CAP_DAC_READ_SEARCH
  - CAP_NET_ADMIN
  egress: null
  endpoints: null
  execs:
  - path: /bin/olm
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress:
  - dns: ''
    dnsNames: null
    identifier: 0a52270744d47da0e770b43cf46a02db90adfdaed097b34c8eacf9c267793a14
    ipAddress: 10.42.0.1
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-8080
      port: 8080
      protocol: TCP
    type: ''
  opens:
  - flags: null
    path: /*/kernel/cap_last_cap
  - flags: null
    path: /*/net/core/somaxconn
  - flags: null
    path: /*/task/⋯/fd
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /⋯
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /⋯/*
  rulePolicies:
    R0001:
      processAllowed:
      - olm
      - runc
    R0002:
      processAllowed:
      - olm
      - runc
    R0004:
      processAllowed:
      - olm
      - runc
    R0005:
      processAllowed:
      - olm
      - runc
    R0006:
      processAllowed:
      - olm
      - runc
    R1017:
      processAllowed:
      - olm
      - runc
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls:
  - accept4
  - arch_prctl
  - bind
  - capget
  - capset
  - chdir
  - clone
  - close
  - close_range
  - connect
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - execve
  - exit
  - faccessat2
  - fchown
  - fcntl
  - fstat
  - fstatfs
  - futex
  - getcwd
  - getdents64
  - getgid
  - getpeername
  - getpid
  - getppid
  - getrandom
  - getrlimit
  - getsockname
  - getsockopt
  - gettid
  - getuid
  - ioctl
  - listen
  - madvise
  - mmap
  - munmap
  - nanosleep
  - newfstatat
  - openat
  - openat2
  - pipe2
  - prctl
  - pread64
  - read
  - readlinkat
  - recvfrom
  - rt_sigaction
  - rt_sigprocmask
  - rt_sigreturn
  - sched_getaffinity
  - sched_yield
  - setgid
  - setgroups
  - setsockopt
  - setuid
  - sigaltstack
  - socket
  - statfs
  - statx
  - tgkill
  - tkill
  - uname
  - unknown
  - write
