apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ContainerProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/managed-by: User
    kubescape.io/resource-size: '53'
    kubescape.io/status: completed
    kubescape.io/sync-checksum: 199567bf56bed19ecc7edd4a9af3dabc08177247a9665cab2ed5973c7cf617db
  name: vizier-operator
  namespace: px-operator
spec:
  architectures: null
  capabilities:
  - CAP_NET_ADMIN
  egress:
  - dns: ''
    dnsNames: null
    identifier: da8e219b26f6e8ddd6c74e3e35355a97a0528bf150772dbbe21aa771733fe958
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
        cluster-id: 6a59ca82-ebaa-4bcd-88b2-41ae2678d72f
        component: vizier
        name: vizier-cloud-connector
        plane: control
        vizier-bootstrap: 'true'
        vizier-name: pixie
    ports:
    - name: TCP-50800
      port: 50800
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: e5e8ca3d76f701a19b7478fdc1c8c24ccc6cef9902b52c8c7e015439e2a1ddf3
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: kube-system
    podSelector:
      matchLabels:
        k8s-app: kube-dns
    ports:
    - name: UDP-53
      port: 53
      protocol: UDP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: 284d617ca3e493147f79f2c7f185037100a9c2636930eec7995122394206e7fe
    ipAddress: 100.103.139.51
    namespaceSelector: null
    podSelector: null
    ports:
    - name: TCP-443
      port: 443
      protocol: TCP
    type: ''
  - dns: ''
    dnsNames: null
    identifier: 2ecd1f4c02e1461f6029b18d649c33cf593473ef52be42e8826414c52906b784
    ipAddress: ''
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: pl
    podSelector:
      matchLabels:
        app: pl-monitoring
        name: pl-nats
        plane: control
        vizier-name: pixie
    ports:
    - name: TCP-8222
      port: 8222
      protocol: TCP
    type: ''
  endpoints: null
  execs:
  - path: /app/src/operator/operator.runfiles/px/src/operator/operator_/operator
  identifiedCallStacks: null
  imageID: ''
  imageTag: ''
  ingress: null
  opens:
  - flags: null
    path: /*/net/core/somaxconn
  - flags: null
    path: /*/task/⋯/fd
  - flags:
    - O_RDONLY
    - O_CLOEXEC
    path: /⋯
  - flags:
    - O_CLOEXEC
    - O_RDONLY
    path: /⋯/*
  rulePolicies:
    R0001:
      processAllowed:
      - operator
      - runc
    R0002:
      processAllowed:
      - operator
      - runc
    R0004:
      processAllowed:
      - operator
      - runc
    R0005:
      processAllowed:
      - operator
      - runc
    R0006:
      processAllowed:
      - operator
      - runc
    R1017:
      processAllowed:
      - operator
      - runc
  seccompProfile:
    spec:
      defaultAction: ''
  syscalls:
  - access
  - clone3
  - close
  - connect
  - epoll_create1
  - epoll_ctl
  - epoll_pwait
  - fcntl
  - fstat
  - futex
  - getdents64
  - getpeername
  - getpid
  - getrandom
  - getrlimit
  - getsockname
  - getsockopt
  - ioctl
  - listen
  - lseek
  - madvise
  - mmap
  - nanosleep
  - newfstatat
  - openat
  - poll
  - pread64
  - prlimit64
  - read
  - readlinkat
  - recvfrom
  - rseq
  - rt_sigreturn
  - sched_getaffinity
  - sched_yield
  - sendmmsg
  - set_robust_list
  - set_tid_address
  - setsockopt
  - socket
  - tgkill
  - uname
  - write
